### ISSUE TITLE
unable to run the demo app

### ISSUE THREAD

**Issue by asangansi** [robfletcher/grails-angular-scaffolding#20]
Please what's the easiest way to run the app in test/apps/grails-ng ?
Trying grails run-app from the grails-ng directory, but no success.
thanks

**Comment by robfletcher** [comment]
Can you give me a bit more to go on? I just do `grails run-app` from that directory.

**Comment by robfletcher** [comment]
That's being brought in by the cloud-foundry plugin which you don't need just to run the app. You could remove the line from BuildConfig.groovy & see if that helps.

## 

Rob Fletcher

**Comment by asangansi** [comment]
Thanks for the quick response. Finally got it going.
Had to download the jackson jar manually. Bu main issues was with grails.plugin.location.'angular-scaffolding' = '../../..'
Took me a while to figure out why I was having failures since I copied out the test/apps/grails-ng to another folder.
can I point grails.plugin.location.'angular-scaffolding' to some where on the web? is it on some repo?

Now looking at building a one page app the way we do it in angular...hope grails will let this happen :)

**Comment by robfletcher** [comment]
You can just install the plugin like any other plugin with ':angular-scaffolding:1.0-SNAPSHOT'

## 

Rob Fletcher

**Comment by asangansi** [comment]
Thanks so much. Issue resolved
