### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by aberbenni** [robfletcher/grails-angular-scaffolding#36]
Hi rob,
  I'm working on a new project with AngularJS and, as a Grails developer I decided to use your plugin.
The plugin project seems abandoned so I decided to work a little bit on it in my fork and I would like to contribute back some modifications:
- upgraded version of AngularJS to 1.2.23
- eliminated jQuery dependency
- renamed directives with gas- prefix
- some bug fixes
- some new bugs...

Here is the fork: https://github.com/aberbenni/grails-angular-scaffolding 
If you think to keep this plugin project alive and you think the work done is useful, please tell me and I will submit a pull request.

Anyone who wants to test the this new code is welcome. Keep in mind that the test app was not upgraded, so for a correct test just scaffold your domain.

**Comment by robfletcher** [comment]
Also it's worth looking at the stuff Craig Burke has been doing around Angular & Grails: craigburke/angular-grails it's much more up-to-date.

**Comment by aberbenni** [comment]
Thanks, I'll give a look at it.
